### PR TITLE
4 cleanup commits

### PR DESCRIPTION
**Pull request by kevmoo**
Suggest using `rebase` to land these...

### CODE REVIEW

**Review by pulyaevskiy — APPROVED** [review]
Thanks for cleaning this up! Looks good.

**Comment by kevmoo** [comment]
@pulyaevskiy – you'll have to pull the lever

**Comment by pulyaevskiy** [comment]
Yeah, sorry for being slow here, in travel mode right now.

**Comment by kevmoo** [comment]
No worries!

**Pull request merged**
