### PR TITLE
Remove `test/**_test.dart` from the default globs

### PR DESCRIPTION
**Pull request by jakemac53**
See https://github.com/dart-lang/test/issues/862 for context - I don't know that there is a reason to bootstrap these files with node?

### CODE REVIEW

**Comment by pulyaevskiy** [comment]
Let me address deprecation warnings and get this build re-ran.

`**_test.dart` might be just a left over from my early experiments.

**Comment by pulyaevskiy** [comment]
Oh, wait... I'm probably still learning here. Is there a convention to use platform postfixes for test files?

All the test files I have are named `*_test.dart` and use `@TestOn('node')`. Not sure why an extra `node_test.dart` needed here?

**Comment by jakemac53** [comment]
The `build_test` package bootstraps the test for each platform - so no you should keep your existing naming schemes. Each of your tests will get corresponding `*.node_test.dart` files, which add node specific bootstrapping code, and now only those files will be compiled with your builder (instead of all test files).

**Comment by pulyaevskiy** [comment]
Thanks for the PR and explanation. Merged and will release shortly.

**Pull request merged**
